=== Getting Started with ClojureScript compiler

At this point, you will surely be very bored with the constant theoretic explanations about the language
itself and will want to write and execute some code. The goal of this section is to provide a little practical
introduction to the _ClojureScript_ compiler.

The _ClojureScript_ compiler takes the source code that has been split over numerous directories and namespaces and
compiles it down to javascript. Today, javascript has great amount of different environments
where it can be executed - each with their own pecularities.

This chapter intends to explain how to use _ClojureScript_ without any additional tooling. This
will help you understand how the compiler works and how you can use it when other tooling is not
available (such as leiningen+cljsbuld or boot).


==== Execution environments

What is an execution environment? An execution environment is an engine where javascript can be
executed. For example, the most popular execution environment is a Browser (Chrome, Firefox, ...)
followed by the second most popular - nodejs/iojs.

There are others, such as Rhino (jdk6+), Nashorn (jdk8), QtQuick (QT),... but none of them have
significant differences from the first two. So, _ClojureScript_ at the moment may compile
code to run in the browser or in nodejs/iojs like environments out of the box.

==== Download the compiler

The _ClojureScript_ compiler is implemented in java, and to use it, you should have jdk8 installed.
_ClojureScript_ itself only requires jdk7, but the standalone compiler that we going to use in this
chapter requires jdk8 which can be found at http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

You can download it using wget:

[source, bash]
----
wget https://github.com/clojure/clojurescript/releases/download/r3211/cljs.jar
----

The _ClojureScript_ compiler is packaged in a standalone executable jar file, so this is the unique
file and jdk8 that you need for compile the _ClojureScript_ source code to javascript.


==== Compile for nodejs/iojs

Let start with a practical example compiling code that will target *nodejs*/*iojs*. For
it you should have installed nodejs or iojs (recommended).

There are different ways to install iojs, but the most recommended way is using nvm (node version
manager). You can read the instructions to install and use nvm on:https://github.com/creationix/nvm[home page].

You can test *iojs* installed in your system with this command:

[source, shell]
----
$ iojs --version
v1.7.1
----

===== Create the example application

For the first step of our practical example, we should create our application directory structure
and populate it with example code.

So start creating the directory tree structure for our "hello world" application:

[source, bash]
----
mkdir -p src/myapp
touch src/myapp/core.cljs
----

Second, write the example code into the previously created `src/myapp/core.cljs` file:

[source, clojure]
----
(ns myapp.core
  (:require [cljs.nodejs :as nodejs]))

(nodejs/enable-util-print!)

(defn -main [& args]
  (println "Hello world!"))

(set! *main-cli-fn* -main)
----

NOTE: Is very important that the declared namespace in the file exactly matches the directory
structure. Is the way _ClojureScript_ structures its source code.


===== Compile the example application

In order to compile that source code, we need a simple build script that instructs the
_ClojureScript_ compiler with the source directory and the output file. _ClojureScript_ has a
lot of other options but at this moment we can ignore that.

Lets create the _build.clj_ file with the following content:

[source, clojure]
----
(require 'cljs.closure)

(cljs.closure/build "src"
 {:output-to "main.js"
  :main 'myapp.core
  :target :nodejs})
----

This is a breif explanation of the used compiler options:

* The `:output-to` parameter indicates to the compiler the destination of the compiled code, in this
  case to the "main.js" file.
* The `:main` property indicates to the compiler the namespace that will acts as the entry point of
  your application when it's executed.
* The `:target` property indicates the platform where you want execute the compiled code. In this case
  we are going to use *iojs* (formerly nodejs). If you omit this parameter the source will be
  compiled to run in the browser environment.

To run the compilation, just execute the following command:

[source, bash]
----
java -cp cljs.jar:src clojure.main build.clj
----

And when it finishes, execute the compiled file using *iojs*:

[source, shell]
----
$ iojs main.js
"Hello world"
----


==== Compile for the Browser

In this section we are going to create a similar "hello world" example application from the
previous section to run in the browser environent. The minimal requirement for it
is just a browser that can execute javascript.

The process is almost the same, the directory structure is the same. The only things that
changes is the entry point of the application and the build script.

Start writing new content to the src/myapp/core.cljs` file:

[source, clojure]
----
(ns myapp.core)

(enable-console-print!)

(println "Hello world!")
----

In the browser environment we do not need a specific entry point for the application,
so the entry point is the entire namespace.


===== Compile the example application

In order to compile the source code to run properly in a browser, overwrite
the _build.clj_ file with the following content:

[source, clojure]
----
(require 'cljs.closure)

(cljs.closure/build "src"
 {:output-to "main.js"
  :output-dir "out/"
  :source-map "main.js.map"
  :main 'myapp.core
  :optimizations :none})
----

This is a brief explanation of the compiler options we're using:

* The `:output-to` parameter indicates to the compiler the destination of the compiled code, in this
  case to the "main.js" file.
* The `:main` property indicates to the compiler the namespace that will act as the entry point of
  your application when it's executed.
* `:source-map` indicates the destination of the source map.
* `:output-dir` indicates the destination directory for all files sources used in a compilation. Is
  just for make source maps works properly with the rest of code, not only your source.
* `:optimizations` indicates the compilation optimization. There are different values for this option
  but that will be covered in following sections in more detail.

To run the compilation, just execute the following command:

[source, bash]
----
java -cp cljs.jar:src clojure.main build.clj
----

This process can take some time, so do not worry, wait a little bit. The jvm bootstrap with Clojure
compiler is slightly slow. In the following sections we will explain how to start a watch process to avoid
constantly starting and stopping this slow process.

While waiting for the compilation, let's create a dummy html file to make it easy to execute our example
app in the browser. Create the _index.html_ file with the following content:

[source, html]
----
<!DOCTYPE html>
<html>
  <header>
    <meta charset="utf-8" />
    <title>Hello World from ClojureScript</title>
  </header>
  <body>
    <script src="main.js"></script>
  </body>
</html>
----


Now, when the compilation finishes and you have the basic html file you can just open it with your favorite
browser and take a look in the development tools console. There should appear the "hello world" message.


==== Watch process

Surely, you have already experienced the slow startup of the _ClojureScript_ compiler. To solve this,
the _ClojureScript_ standalone compiler also comes with tools to start a process that watches the changes
in some directory and perform an incremental compilation.

Start creating another build script, but in this case name it _watch.clj_:

[source, clojure]
----
(require 'cljs.closure)

(cljs.closure/watch "src"
 {:output-to "main.js"
  :output-dir "out/"
  :source-map "main.js.map"
  :main 'myapp.core
  :optimizations :none})
----

Now, execute that script like any other that you have executed in previous sections:

[source, bash]
----
$ java -cp cljs.jar:src clojure.main build.clj
Building ...
Reading analysis cache for jar:file:/home/niwi/cljsbook/playground/cljs.jar!/cljs/core.cljs
Compiling out/cljs/core.cljs
Using cached cljs.core out/cljs/core.cljs
... done. Elapsed 0.8354759 seconds
Watching paths: /home/niwi/cljsbook/playground/src

Change detected, recompiling ...
Compiling src/myapp/core.cljs
Compiling out/cljs/core.cljs
Using cached cljs.core out/cljs/core.cljs
... done. Elapsed 0.191963443 seconds
----

You can observe that in the second compilation, the time is drastically reduced. Another advantage
of this method is that it's a little bit more verbose.


==== Optimization levels

The _ClojureScript_ compiler has different level of optimizations. Behind the scenes, those compilation
levels are coming from Google Closure Compiler.

A very inacurate overview of the compilation process is:

1. The reader reads the code and makes some analysis. This process can raise some warnings
   during its phase.
2. Then, the _ClojureScript_ compiler emits javascript code. The result of that is one javascript
   file for each cljs file.
3. The generated files pases throught the Closure Compiler that depending on the optimization level,
   and other options (sourcemaps, output dir output to, ...) generates the final output.

The final output dependends strictly on the optimization level.


===== none

Implies that closure compiler is noop, just writes the files as is, without any additional
optimization applied to the source code. This optimization level is manadatory if you are targeting
*nodejs* or *iojs*, and the appropiate in development mode when your code targets the browser.


===== whitespace

This optimization level consists of concatenating the compiled files in an appropriate order, removing
line breaks and other whitespaces and generating the output as one unique file.

It also has some compilation speed penality, resulting in slower compilations. In any case it is not
very very slow and is completely usable in small/medium applications.


===== simple

The simple compilation level implies (includes) all transformations from whitespace optimization and
additionally performs optimizations within expressions and functions, including renaming local variables
and function parameters to shorter names.

Compilation with `:simple` optimization always preserves the functionality of syntactically valid
JavaScript, so it does not interfere with the interaction between the compiled _ClojureScript_ and
other JavaScript.

===== advanced

TBD


=== Working with the REPL

TBD


=== Build & Dependency management tools

==== Getting started with leiningen.

TBD

==== Getting started with boot.

TBD


=== The Closure Library

TBD


=== Browser based development

TBD

//^ A little guide and notes about implications of developing for web
//^ environments (optimizations, third party libraries, modularization, ...)

==== Using third party javascript libraries

TBD


====  Modularizing your code

//^ Mainly related to google closure modules and slightly related to web based development
//^ Maybe this is not the chapter for this section.

TBD



=== Developing a library

//^ A little guide and implications of developing a library for clojurescript.

TBD


=== Unit testing

TBD
