= ClojureScript Unraveled
Andrey Antukh & Alejandro Gomez
v1.0
:toc: left
:doctype: book
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:
//^:source-highlighter: coderay
//^:listing-caption: Listing

== Introduction

This chapter will be a first introduction to the clojure ecosystem, and intends to explain
the philosophy behind of it.

include::philosophy.adoc[]


== The language.

This chapter will be a little introduction to ClojureScript without assumptions about previous
knowledge of the Clojure language, providing a quick tour over all the things you will need to know
in order to understand the rest of this book.

This is an incomplete list of topics that will be covered in this chapter:

* Syntax
* The base types
* Collections
* Functions
* Loops & Blocks
* Destructuring
* Namespaces
* Custom Data Types
* Polymorphic constructions
* Interoperability with host
* Macros

include::language.adoc[]

== Tooling & Compiler

This chapter will cover a little introduction to existing tooling for making things easy when
developing using ClojureScript. It will cover:

* Leiningen and cljsbuild
* Google Closure Library
* Modules
* Unit testing
* Library development
* Browser based development
* Server based development

== Mixed Bag

This chapter will cover miscelaneous topics that are not classified in the previous ones. This is a "catchall"
section and will touch a bunch of heterogeneus topics like:

* Async primitives using _core.async_ library.
* Pattern matching with _core.match_ library.
* Error handling using _cats_ library.
* Web development using Om library.
* Share code betwen clojure and clojurescript.
