= ClojureScript Unraveled
Andrey Antukh & Alejandro Gomez
v1.0
:toc: left
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing

== Language introduction

This chapter will cover a little introduction to the language without supositions of additional
knowledge of clojure language, providing a quick tour over all the things you will need to know
or understand for the rest of this book.

This is a incomplete list of themes that will be touched in this chapter:

* The base types
* Collections
* Functions
* Loops & Blocks
* Destructuring
* Namespaces
* Data Types
* Polymorphic constructions
* Interoperability with host

include::language.adoc[]

== Tooling & Compiler

This chapter will cover a little introduction to existing tooling for make things easy in time
of developing using clojurescript. And it will cover:

* Leiningen and cljsbuild
* Google Closure Library
* Modules
* Unit testing
* Library development
* Browser based development
* Server based development

== Mixed Bag

This chapter will covert all other themes that are not classified in previos ones. This is a "catchall"
section and will touch a big bunch of heterogeneus themes like:

* Async primitives using _clore.async_ library.
* Pattern martching with _core.match_ library.
* Error handling using _cats_ library.
* Web development using Om library.


