= ClojureScript Unraveled
Andrey Antukh <niwi@niwi.be>; Alejandro Gomez <alejandro@dialelo.com>
v1, 2015-05-04
:toc: left
:toclevels: 3
:doctype: book
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:idseparator: -
:idprefix:
:sectlinks:
//^:source-highlighter: coderay
//^:listing-caption: Listing

== Introduction

This chapter is an introduction to the Clojure ecosystem, and intends to explain
the philosophy behind it.

include::philosophy.adoc[]


== The language.

This chapter will be a little introduction to ClojureScript without assumptions about previous
knowledge of the Clojure language, providing a quick tour over all the things you will need to know
in order to understand the rest of this book.

include::language.adoc[]


== Tooling & Compiler

This chapter will cover a little introduction to existing tooling for making things easy when
developing using ClojureScript. It will cover:

* Using the repl
* Leiningen and cljsbuild
* Google Closure Library
* Modules
* Unit testing
* Library development
* Browser based development
* Server based development

Unlike the previous chapter, this chapter intends to tell different stories each independent of each other.

include::compiler.adoc[]


== Mixed Bag

This chapter will cover miscellaneous topics that are not classified in the previous ones. This is a
"catchall" section and will touch a bunch of heterogeneus topics like:

* Async primitives using the _core.async_ library.
* Working with promises.
* Error handling using the _cats_ library.
* Pattern matching with the _core.match_ library.
* Web development using the Om library.
* Share code betwen clojure and clojurescript.

include::mixedbag.adoc[]
