=== First steps with lisp syntax

TBD


=== The base data types.

The ClojureScript language has a rich set of data types like most programmig languages. It provides
scalar datatypes that will be very familiar for you such as numbers, strings, floats. But, also
provides a great amount of others that maybe are not well known such as symbols, keywords, regex,
vars, atoms, volatiles...

_ClojureScript_ embrases the host language, and as possible it uses the host provided types. In this
case: numbers and strings are used as is and them behaves in same way as in javascript.


==== Numbers

In _ClojureScript_ the numbers includes both: integers and floating points. But, knowing that
_ClojureScript_ is a guest language that compiles to javascript, having integers is an ilusion.
Because the javascript language treats all numbers as floating points values.

Like in any other languages, the numbers in _ClojureScript_ are represented in following way:

[source, clojure]
----
23
+23
-100
1.7
-2
33e8
12e-14
3.2e-4
----


==== Keywords

Keywords in _ClojureScript_ are objecs that always evaluate to themselves. Them are usually
used in map data structures for reprensent in a most efficient way to the keys.

[source, clojure]
----
:foobar
:2
:?
:foo/bar
----

As you can see, the keyword are all prefixed with `:`, but this char is only part
of literal syntax and is not part of the name of the object.

You also can create a keyword calling a function `keyword`. Do not worry if you do not understand
or something is not clear in the following example, the functions are discussed some chapters
below.

[source, clojure]
----
(keyword "foo")
;; => :foo
----


==== Symbols

The symbols in _ClojureScript_ are very very similar to now known *Keywords*. But them
instead of evaluating to themselves, are evalutated to something that them refers, that
can be function, variables, ...

Them are represented with something that not star with a number

[source, clojure]
----
sample-symbol
othersymbol
f1
----

Do not worry if you do not understand clearly this part, symbols are used un almost
all examples and you will have the oportunity to undesarstand them in a practical way,
with examples.


==== Strings

Nothing new we can explain about strings that you do not known. In _ClojureScript_ them
are work like in any other language. Them are immutable.

And in this concrete case are the same as in javascript:

[source, clojure]
----
"A example of a string"
----

The pecularity of Strings on _ClojureScript_ is due to lisp syntax, and is that you don't need
additional syntax for multiline strings:

[source, clojure]
----
"This is a multiline
      string in ClojureScript."
----

==== Characters

_ClojureScript_ also has a representation for one character and it has a literal syntax for represent
them.

[source, clojure]
----
\a        ; The lowercase a character
\newline  ; The new line character
----

As its host does not a clear representation for character type, in _ClojureScript_ behind the scenes
one character is a simple string with one character.


==== Collections

As usual, the second big step on explaining one language, is explain its collections and collection
abstractions. The _ClojureScript_ is not an exception in this rule.

_ClojureScript_ comes with great bunch of different collections. The main difference of _ClojureScript_
collections with other languages is that them are persistent and immutable.

//^ TODO: add link and documentation for persistence and immutability.

===== Lists

TBD

===== Vectors

TBD

===== Maps

TBD

===== Sets

TBD