=== First steps with lisp syntax

Invented by John McCarthy in 1958, Lisp is one of the oldest programming languages that is still
around. It has evolved into a whole lot of derivatives called dialects and ClojureScript is
one of them. It's a programming language written in its own data structures, originally lists enclosed in
parenthesis, but Clojure(Script) has evolved the Lisp syntax with more data structures making
it more pleasant to write and read.

A list with a function in the first position is used for calling a function in ClojureScript:

[source, clojure]
----
(+ 1 2 3)
;; => 6
----

In the example above we're applying the addition function `+` to the arguments 1, 2 and 3. ClojureScript
allows many unusual characters like `?` or `-` in symbol names which makes it easier to read:

[source, clojure]
----
(zero? 0)
;; => true
----

For distinguishing function calls and lists, we can quote lists for turning off evaluation. The quoted
lists will be treat as data instead of as a function call:

[source, clojure]
----
'(+ 1 2 3)
;; => (+ 1 2 3)
----

ClojureScript uses more than lists for its syntax, the full details will be covered later but here is an
example of the usage of a vector (enclosed in brackets) for defining local bindings:

[source, clojure]
----
(let [x 1
      y 2
      z 3]
  (+ x y x))
;; => 6
----

This is practically all the syntax we need to know for using not only ClojureScript, but any Lisp. Being
written in its own data structures (often referred to as homoiconicity) is a great property since the syntax
is uniform and simple; also, code generation via macros is easier than in any language, giving us
plenty of power for extending the language to our needs.

=== The base data types.

The ClojureScript language has a rich set of data types like most programmig languages. It provides
scalar datatypes that will be very familiar for you such as numbers, strings, floats. But, also
provides a great amount of others that maybe are not well known such as symbols, keywords, regex,
vars, atoms, volatiles...

_ClojureScript_ embrases the host language, and as possible it uses the host provided types. In this
case: numbers and strings are used as is and them behaves in same way as in javascript.


==== Numbers

In _ClojureScript_ the numbers includes both: integers and floating points. But, knowing that
_ClojureScript_ is a guest language that compiles to javascript, having integers is an ilusion.
Because the javascript language treats all numbers as floating points values.

Like in any other languages, the numbers in _ClojureScript_ are represented in following way:

[source, clojure]
----
23
+23
-100
1.7
-2
33e8
12e-14
3.2e-4
----


==== Keywords

Keywords in _ClojureScript_ are objecs that always evaluate to themselves. Them are usually
used in map data structures for reprensent in a most efficient way to the keys.

[source, clojure]
----
:foobar
:2
:?
:foo/bar
----

As you can see, the keyword are all prefixed with `:`, but this char is only part
of literal syntax and is not part of the name of the object.

You also can create a keyword calling a function `keyword`. Do not worry if you do not understand
or something is not clear in the following example, the functions are discussed some chapters
below.

[source, clojure]
----
(keyword "foo")
;; => :foo
----


==== Symbols

The symbols in _ClojureScript_ are very very similar to now known *Keywords*. But them
instead of evaluating to themselves, are evalutated to something that them refers, that
can be function, variables, ...

Them are represented with something that not star with a number

[source, clojure]
----
sample-symbol
othersymbol
f1
----

Do not worry if you do not understand clearly this part, symbols are used un almost
all examples and you will have the oportunity to undesarstand them in a practical way,
with examples.


==== Strings

Nothing new we can explain about strings that you do not known. In _ClojureScript_ them
are work like in any other language. Them are immutable.

And in this concrete case are the same as in javascript:

[source, clojure]
----
"A example of a string"
----

The pecularity of Strings on _ClojureScript_ is due to lisp syntax, and is that you don't need
additional syntax for multiline strings:

[source, clojure]
----
"This is a multiline
      string in ClojureScript."
----

==== Characters

_ClojureScript_ also has a representation for one character and it has a literal syntax for represent
them.

[source, clojure]
----
\a        ; The lowercase a character
\newline  ; The new line character
----

As its host does not a clear representation for character type, in _ClojureScript_ behind the scenes
one character is a simple string with one character.


==== Collections

As usual, the second big step on explaining one language, is explain its collections and collection
abstractions. The _ClojureScript_ is not an exception in this rule.

_ClojureScript_ comes with great bunch of different collections. The main difference of _ClojureScript_
collections with other languages is that them are persistent and immutable.

But before venture of all these (maybe) unknown concepts, we'll go to make a high level overview
of existing collection types in _ClojureScript_.


===== Lists

This is a clasic collection type in lisp languages. _ClojureScript_ is not an exception. List is the
simplest collection data structure in _ClojureScript_. Lists can contain items of any type, including
other collections.

Lists in _ClojureScript_ are repsesented with parentheses as its literal syntax:

[source, clojure]
----
'(1 2 3 4 5)
'(:foo :bar 2)
----

As you can observe, all list examples are prefixed with `'` char. This is because lists in lisp like
languages are often used for express expressions forms such as function or macro calls. In that case
the first item should be a symbol that will evaluate to a something callable and the rest of list
elemenents will be a function parameters.

[source, clojure]
----
(inc 1)
;; => 2

'(inc 1)
;; => (inc 1)
----

As you see, if you will evaluate the `(inc 1)` without prefixing it with `'` char, it will resolve
the `inc` symbol to the *inc* function and will execute it with `1` as first parameter. Resulting
in a `2` as return value.

Lists have the pecularity that they are very efficient if you access to it in a sequence mode or
access to its first elements but are not very good option if you need random (index) acces to its
elements.


===== Vectors

Like lists, *Vectors*  store a series of values, but in this case with very efficient index access
to its elements and its elements in difference with list are evaluated in order. Do not worry, in
below chapters we'll go depth in details but at this moment is more that enough.

Vectors uses square brakets for the literal syntax, let see some examples:

[source, clojure]
----
[:foo :bar]
[3 4 5 nil]
----

Like lists, vectors can contain objects of any type, as you can observe the previos example.


===== Maps

Maps is a collection abstraction that allows store unique keys associated with one value. In other
languages are commonly known as hash-maps or dicts. Maps in _ClojureScript_ uses a
curly braces as literal syntax.

[source, clojure]
----
{:foo "bar", :baz 2}
{:foobar [:a :b :c]}
----

NOTE: Commas are frequently used for separate a key value pair but are completelly optional. In
_ClojureScript_ syntax, comas are treated like spaces.

Like Vectors, every item in a map literal is evaluated before the result is stored in a map, but
the order of evaluation is not guaranteed.


===== Sets

And finally, *Sets*.

Sets stores in an unordered way zero or more unique items of any type. They,
like maps, uses curly braces for its literal syntax with difference that uses a `#` as leading
character:

[source, clojure]
----
#{1 2 3 :foo :bar}
----

In below chapters we'll go depth in sets and other collection types explained in this chapter.


=== Vars

_ClojureScript_ is a mostly functional language and focused in immutability. Becuase of that, it does
not has the concept of variables. The most closest analogy to variables are *vars*. The vars are
represented by symbols and stores a single value together with metadata.

You can define a var using a `def` special form:

[source, clojure]
----
(def x 22)
(def y [1 2 3])
----

The vars are always top level in the namespace. If you use `def` in a function call, the var will be defined
at the namespace level.


=== Functions

==== The first contact

It's time of make things happen. In _ClojureScript_, a function are first-class type. It behaves
like any other type, you can pass it as parameter, you can return it as value, always respecting
the lexical scope. _ClojureScript_ also has some features from dynamic scope but this will be discused
in other section.

If you want know more about scopes, this link:http://en.wikipedia.org/wiki/Scope_%28computer_science[wikipedia article]
is ver extensive and explain very well different types of scope.

As _ClojureScript_ is a lisp dialect, it uses the prefix notation for calling a function:

[source, clojure]
----
(inc 1)
;; => 2
----

The `inc` is a function and is part of _ClojureScript_ runtime, and `1` is a first positional
argument for the `inc` function.

[source, clojure]
----
(+ 1 2 3)
;; => 6
----

The `+` symbol represents a `add` function, in ALGOL type of languages is an operator and only
allows two parameters.

The prefix notation has huge advantages, some of them not alwats obvious. _ClojureScript_ does not
has distinction between a function and operator, everything is a function. The inmediate advantage
is that the prefix notation allows an arbitrary number of arguments per "operator". Also, it eliminates
per complete the problem of operator precedence.

==== Defining own functions

The function can be defined with `fn` special form. This is aspect of function definition:

[source, clojure]
----
(fn [param1 param2]
  (+ (inc param1) (inc param2)))
----

You can define a function and call it in same time (in a single expression):

[source, clojure]
----
((fn [x] (inc x)) 1)
;; => 2
----

Let start creating named functions. But that is means named function really? Is very simple,
as in _ClojureScript_ functions are fist-class and behaves like any other value, naming a function
is just store it in a var:

[source, clojure]
----
(def myinc (fn [x] (+ x 1)))

(myinc 1)
;; => 2
----

_ClojureScript_ also offers the `defn` macro as a little sugar syntax for make function definition
more idiomatic:

[source, clojure]
----
(defn myinc
  "Self defined version of `inc`."
  [x]
  (+ x 1))
----

==== Function with multiple arities

_ClojureScript_ also comes with ability to define functions with arbitrary number of arities. The
syntax is almost the same as define standard function with the difference that it has more that
one body.

Let see an example, surelly it will explain it much better:

[source, clojure]
----
(defn myinc
  "Self dined version of parametrized `inc`."
  ([x] (myinc x 1))
  ([x increment]
   (+ x increment)))
----

And there some examples using the previously defined multi arity function. I can observe that
if you call a function with wrong number of parameters the compiler will emit an error about that:

[source, clojure]
----
(myinc 1)
;; => 1

(myinc 1 3)
;; => 4

(myinc 1 3 3)
;; Compiler error
----

[NOTE]
Explaining the "arity" is out of scope of this book, however you can read about that in this
link:http://en.wikipedia.org/wiki/Arity[wikipedia article].


==== Variadic functions

An other way to accept multiple parameters is defining variadic functions. Variadic functions
are functions that will be able accept arbitrary number of arguments:

[source, clojure]
----
(defn my-variadic-set
  [& params]
  (set params))

(my-variadic-set 1 2 3 1)
;; => #{1 2 3}
----

The way to denone a variadic function is using the `&` simbol prefix on its arguments vector.


==== Short syntax for anonymous functions

_ClojureScript_ provides a shorter syntax for define anonymos (and almost always one liner) functions
using the `#()` reader macro. Reader macros are "special" expressions that in compile time will be
transformed to the apropiate language form. In this case to some expression that uses `fn` special
form.

[source, clojure]
----
(def my-set #(set %1 %2))

(my-set 1 2)
;; => #{1 2}
----

The `%1`, `%2`, `%N` are simple markers for parameter positions that are implicitly declared when
the reader macro will be interpreted and converted to `fn` expression.

Also, if a function only accepts one argument, you can ommit the number after `%` symbol, the
function `#(set %1)` can be written `++#++(set %)`.

Additionaly, this syntax also supports the variadic form with `%&` symbol:

[source, clojure]
----
(def my-variadic-set #(set %&))

(my-variadic-set 1 2 2)
;; => #{1 2}
----

=== Flow control

_ClojureScript_ has a great different approaches for flow control.

==== Branching with `if`

Let start with a basic one: `if`. In _ClojureScript_ the `if` is an expression and not an
statement, and it has three parametes: first one the condition expression, the second one
a expression that will evalute if a condition expression will evalute in a logical true,
and the third one will evaluated otherwise.

[source, clojure]
----
(defn mypos?
  [x]
  (if (pos? x)
    "positive"
    "negative"))

(mypos? 1)
;; => "positive"

(mypos? -1)
;; => "negative"
----

If you want do more that one thing in one of two expressions, you can use block expression `do`, that
is will explained in next section.


==== Branching with `cond`

Sometimes, the `if` expression can be slightly limited because it does not have the "else if" part
for add more that one condition. The cond comes to the rescue.

With `cond` expression, you can define multiple conditions:

[source, clojure]
----
(defn mypos?
  [x]
  (cond
    (> x 0) "positive"
    (< x 0) "negative"
    :else "zero"))

(mypos? 0)
;; => "zero"

(mypos? -2)
;; => "negative"
----

Also, cond has an other form, called `condp`, that works very similar to the simple `cond`
but looks more cleaner when a predicate is always the same for all conditions:

[source, clojure]
----
(defn translate-lang-code
  [code]
  (condp = (keyword code)
    :es "Spanish"
    :en "English"
    "Unknown"))

(translate-lang-code "en")
;; => "English"

(translate-lang-code "fr")
;; => "Unknown"
----


==== Branching with `case`

The `case` branching expression has very similar use case that our previous example with
`condp`. The main difference is that, case always uses the `=` predicate/function and its
branching values are evaluated at compile time. This results in a more prerformant form
that `cond` or `condp` but has the disadvantage of that the condition value should be
a static value.

Let see the same example as previous one but using `case`:

[source, clojure]
----
(defn translate-lang-code
  [code]
  (case code
    "es" "Spanish"
    "es" "English"
    "Unknown"))

(translate-lang-code "en")
;; => "English"

(translate-lang-code "fr")
;; => "Unknown"
----


=== Locals, Blocks and Loops

==== Locals

_ClojureScript_ does not has the variables concepts, but it does have locals. Locals as per
usual, are immutable and if you try mutate them, the compiller will throw an error.

The locals are defined with `let` expression. It starts with a vector as first parameter
followed by arbitrary number of expresions. The first parameter should contain a arbitrary
number of pairs that starts with a binding form followed of an expression whose value will
be bound to this new local for the remainer of the let expression.

[source, clojure]
----
(let [x (inc 1)
      y (+ x 1)]
  (println "Simple message from body of let")
  (* x y))
;; => 6
----

==== Blocks

The blocks in _ClojureScript_ can be done using the `do` expression and is ususally used
for side effects, like printing something in console or write a log in a logger. Something
for that the return value is not necesary.

The `do` expression accept as parameter an arbitrary number of other expressions but return
the return value only from the last one:

[source, clojure]
----
(do
   (println "hello world")
   (println "hola mundo")
   (+ 1 2))
;; => 3
----

The `let` expression, explained just in previous section, the body is very similar to the
`do` expression. In fact, it is called that is has an implicit `do`.


==== Loops

The functional approach of _ClojureScript_, this causes that it does not have standard,
well known statements based loops. The loops in clojurescript are handled using recursion.
The recursion sometimes requires additional thinking about how model your problem in
a slightly different way than imperative languages.

Also, many of the common patterns for which `for` is used in other languages are achieved
through higher-order functions.

===== Looping with loop/recur

Let's take a look at how to express loops using recursions with the `loop` and `recur` forms.
`loop` defines a possibly empty list of bindings (notice the symmetry with `let`) and `recur`
jumps execution after the looping point with new values for those bindings.

Let's see an example:

[source, clojure]
----
(loop [x 0]
   (println "Looping with " x)
   (if (= x 2)
     (println "Done looping!")
     (recur (inc x))))
;; => "Looping with 0"
;; => "Looping with 1"
;; => "Looping with 2"
;; => "Done looping!"
----

In the above snippet, we bind the name `x` to the value `0` and execute the body. Since the
condition is not met the first time is run we `recur`, incrementing the binding value with
the `inc` function. We do this once more until the condition is met and, since there aren't
more `recur` calls, exit the loop.

Note that `loop` isn't the only point we can `recur` too, using `recur` inside a function
executes the body of the function recursively with the new bindings:

[source, clojure]
----
(defn recursive-function [x]
   (if (= x 2)
     (println "Done looping!")
     (recur (inc x))))

(recursive-function 0)
;; => "Looping with 0"
;; => "Looping with 1"
;; => "Looping with 2"
;; => "Done looping!"
----

===== Replacing for loops with `map`, `filter` and `reduce`

TODO

=== Collection types.

TBD

//^ All about collection types, immutability, persistence, seq abstraction...


=== Destructuring

TBD


=== Namespaces

TBD


=== Data types

TBD


=== Polymorphism & Polymorphic constructions

TBD


=== Host interoperability

TBD


=== A little overview of macros

TBD