=== First contact

_ClojureScript_ is an implementation of the Clojure programming language that
targets JavaScript. Because of this it can run in many different execution
environments including web browsers, Node.js, io.js, and Nashhorn.

Unlike other languages that intend to _compile_ to JavaScript (like TypeScript,
FunScript or CoffeeScript), ClojureScript is designed to use JavaScript like bytecode. It embraces
functional programming, and has very safe and consistent defaults.

Another big difference (and in my opinion a big advantage) over other languages is that Clojure
is designed to be a guest. It is a language without its own virtual machine that
can be easy adapted to differences between its execution environments.

[comment]
But, what does this mean? It means that ClojureScript does not preserve the semantics of its host language,
but imposes its own. The result of compiling Clojure (unlike what happens with other "transpilers")
does not always result in direct 1:1 translation your code to compiled code. Maybe you think that
this will make debugging difficult, but in in modern environments source maps work very well and
this practically hides the need to inspect compiled code.


TBD


=== The pillars of the language

TBD


=== Why host on JavaScript?

TBD
